version: '3'
services:
  db:
    image: mdillon/postgis 
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=123
  wait:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432
  beeru:
    image: caires/beeru:v0.0.1
    environment:
      - PG_CONNECTION=user=postgres dbname=postgres sslmode=disable password=123 host=db
    ports:
      - "8000:8000"
    depends_on:
      - wait